name: prayer_time
description: "A new kill-proof classic prayer time application."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  adhan: ^2.0.0+1
  geolocator: ^10.1.0
  android_alarm_manager_plus: ^3.0.3
  flutter_local_notifications: ^17.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
