name: Prayer Times CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Flutter (Latest Stable)
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Install Dependencies
      run: flutter pub get

    # 1. ٹیسٹنگ والی APK بنانا (یہ پاس ہو جاتی ہے)
    - name: Build APK for Local Testing
      run: flutter build apk --debug

    # جادوئی تبدیلی: اے پی کے بنتے ہی فوراً اپلوڈ کر دیں تاکہ تالا محفوظ ہو جائے!
    - name: Upload Testing APK to GitHub Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: PrayerTime-Testing-APK
        path: build/app/outputs/flutter-apk/app-debug.apk

    # 2. پلے اسٹور کے لیے فائنل AAB بنانا (اگر یہ فیل بھی ہو تو پرواہ نہیں)
    - name: Build App Bundle (AAB)
      run: flutter build appbundle --release
      env:
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

    - name: Upload App Bundle to GitHub Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: PrayerTime-PlayStore-AAB
        path: build/app/outputs/bundle/release/app-release.aab
