name: Flutter Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    # 🌟 یہ ہے وہ ٹرک: پاسورڈ کو انوائرمنٹ (env) کے ذریعے پاس کرنا
    - name: Create key.properties
      env:
        SECRET_STORE_PASS: ${{ secrets.STORE_PASSWORD }}
        SECRET_KEY_PASS: ${{ secrets.KEY_PASSWORD }}
      run: |
        echo "storePassword=$SECRET_STORE_PASS" > android/key.properties
        echo "keyPassword=$SECRET_KEY_PASS" >> android/key.properties
        echo "keyAlias=upload" >> android/key.properties
        echo "storeFile=upload-keystore.jks" >> android/key.properties

    - name: Install dependencies
      run: flutter pub get

    - name: Build AAB
      run: flutter build appbundle --release

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: prayer-times-app-release
        path: build/app/outputs/bundle/release/app-release.aab
