name: Flutter Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    # اب یہ طریقہ پاسورڈ کے اسپیشل کیریکٹرز کو بالکل محفوظ رکھے گا
    - name: Create key.properties
      run: |
        cat << 'SECRET_EOF' > android/key.properties
        storePassword=${{ secrets.STORE_PASSWORD }}
        keyPassword=${{ secrets.KEY_PASSWORD }}
        keyAlias=upload
        storeFile=upload-keystore.jks
        SECRET_EOF

    - name: Install dependencies
      run: flutter pub get

    - name: Build AAB
      run: flutter build appbundle --release

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: prayer-times-app-release
        path: build/app/outputs/bundle/release/app-release.aab
