name: Flutter Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    # 🌟 یہاں پاسورڈ بغیر کسی فائل کے سیدھے گریڈل بلڈ کو مل جائیں گے
    - name: Build AAB
      env:
        STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      run: flutter build appbundle --release

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: prayer-times-app-release
        path: build/app/outputs/bundle/release/app-release.aab
